apiVersion: v1
kind: Service
metadata:
  name: devopsclasscodes-service
  namespace: devopsclasscodes
  labels:
    app: devopsclasscodes
spec:
  selector:
    app: devopsclasscodes
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    