apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopsclasscodes-ingress
  namespace: devopsclasscodes
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - example.foo.com
    secretName: secret-tls
  rules:
  - host: "example.foo.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: devopsclasscodes-service
            port:
              number: 8080